[workspace]
members = ["capturer-svr"]
resolver = "3"

[workspace.dependencies]
clap = "4.5.53"
log = "0.4.28"
serde = "1.0.228"
serde_with = "3.16.0"
tokio = "1.48.0"
actix-web = "4.12.0"
validator = "0.20.0"
utoipa = "5.4.0"
utoipa-swagger-ui = "9.0.2"
ffmpeg-next = "8.0.0"
image = "0.25.9"
robotech = "0.10.0"

[patch.crates-io]
robotech = { path = "../robotech-rs" }
