[workspace]
members = ["capturer-svr"]
resolver = "3"

[workspace.dependencies]
log = "0.4.28"
clap = "4.5.53"
chrono = "0.4.42"
serde = "1.0.228"
serde_with = "3.16.1"
serde_json = "1.0.145"
tokio = "1.48.0"
actix-web = "4.12.1"
validator = "0.20.0"
utoipa = "5.4.0"
utoipa-swagger-ui = "9.0.2"
ffmpeg-next = "8.0.0"
image = "0.25.9"
robotech = "0.10.1"
oss-api = "0.2.1"

[patch.crates-io]
robotech = { path = "../robotech-rs" }
oss-api = { path = "../oss-rs/oss-api" }
